# Generated by Django 5.2.5 on 2025-10-06 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MONTO_BRUTO', 'Monto Bruto'), ('FACTOR', 'Factor')], max_length=50)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('factor', models.FloatField(blank=True, null=True)),
                ('tipo_ingreso', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='core.corredor')),
            ],
        ),
    ]
